export const JOBS = [
  {
    id: 1,
    title: "Front-end Developer",
    company: "Pasha Real Estate",
    salary: "2500 ₼",
    location: "Bakı",
    date: "2026-02-21",
    type: "Full-time",
    experience: "2-4 il",
    logo: "PE",
    logoColor: "#1a73e8",
    tags: ["React", "TypeScript", "CSS"],
    status: "aktivdir",
  },
  {
    id: 2,
    title: "Grafik & Reels Dizayner",
    company: "Aviashop Travel",
    salary: "Razılaşma ilə",
    location: "Quba",
    date: "2026-02-21",
    type: "Freelance",
    experience: "1-2 il",
    logo: "AT",
    logoColor: "#e53935",
    tags: ["Figma", "Photoshop"],
    status: "aktivdir",
  },
  {
    id: 3,
    title: "Sürücü - Ekspeditor",
    company: "Az Kağız Və Karton Mmc",
    salary: "Razılaşma ilə",
    location: "Quba",
    date: "2026-02-21",
    type: "Full-time",
    experience: "3+ il",
    logo: "AK",
    logoColor: "#f57c00",
    tags: ["B kateqoriya", "Logistika"],
    status: "aktivdir",
  },
  {
    id: 4,
    title: "Təlim Və Personalın İnkişafı",
    company: "Prime Accessories Mağazalar",
    salary: "1500 ₼",
    location: "Bakı",
    date: "2026-02-21",
    type: "Full-time",
    experience: "2-3 il",
    logo: "PA",
    logoColor: "#6a1b9a",
    tags: ["HR", "Təlim"],
    status: "premium",
  },
  {
    id: 5,
    title: "Satış Məsləhətçisi",
    company: "Prime Accessories Mağazalar",
    salary: "600 ₼",
    location: "Bakı",
    date: "2026-02-20",
    type: "Full-time",
    experience: "0-1 il",
    logo: "PA",
    logoColor: "#6a1b9a",
    tags: ["Satış", "Müştəri xidməti"],
    status: "aktivdir",
  },
  {
    id: 6,
    title: "Mechanical Technical Office Engineer",
    company: "Pasha Real Estate",
    salary: "Razılaşma ilə",
    location: "Şuşa",
    date: "2026-02-21",
    type: "Full-time",
    experience: "3-5 il",
    logo: "PE",
    logoColor: "#1a73e8",
    tags: ["AutoCAD", "Mühəndislik"],
    status: "aktivdir",
  },
];